export const SAVE_SEARCH_RESULTS = 'SAVE_SEARCH_RESULTS';
export const INCREASE_SEARCH_RESULTS_COUNT = 'INCREASE_SEARCH_RESULTS_COUNT';
export const RESET_SEARCH_RESULTS_COUNT = 'RESET_SEARCH_RESULTS_COUNT';